version: '3'
services:
  monorail:
    build: .
    ports:
      - "8080:8080"
      - "8484:8484"
    environment:
      PORT: 8080
      PRIVATE_PORT: 8484
      GH_SECRET: "${GH_SECRET}"
      GH_TOKEN: "${GH_TOKEN}"
      SLACK_URL: "${SLACK_URL}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION:-us-east-1}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    volumes:
      - ./local-config:/app/config/

  monorail-test:
    build: .
    volumes:
      - ./local-config:/app/config/
    command: npm run test
